version: '3.9'

services:
  web:
    image: python:3.12
    container_name: django_app
    command: >
      sh -c "pip install -r requirements.txt &&
             python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 chat.asgi:application"
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: meupostgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: chatdb
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: meuredis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
